// Generated by CoffeeScript 1.6.3
(function() {
  (function() {
    var i, lastTime, vendors, w, _i, _ref;
    w = window;
    lastTime = 0;
    vendors = ['webkit', 'moz'];
    if (!w.requestAnimationFrame) {
      for (i = _i = 0, _ref = vendors.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
        w.requestAnimationFrame = w["" + vendors[i] + "RequestAnimationFrame"];
        w.cancelAnimationFrame = w["" + vendors[i] + "CancelAnimationFrame"] || w["" + vendors[i] + "CancelRequestAnimationFrame"];
      }
    }
    if (!w.requestAnimationFrame) {
      w.requestAnimationFrame = function(callback, element) {
        var currTime, id, timeToCall;
        currTime = new Date().getTime();
        timeToCall = Math.max(0, 16 - (currTime - lastTime));
        id = w.setTimeout(function() {
          return callback(currTime + timeToCall);
        }, timeToCall);
        lastTime = currTime + timeToCall;
        return id;
      };
    }
    if (!w.cancelAnimationFrame) {
      return w.cancelAnimationFrame = function(id) {
        return clearTimeout(id);
      };
    }
  })();

}).call(this);

/*
//@ sourceMappingURL=rAF.map
*/
